/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fumera.viewer;

import fumera.controller.JavaDBtoObj;
import fumera.model.Siparis;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tansel
 */
public class SiparisEkranı extends javax.swing.JFrame {

    // DATA LAYER
    private ArrayList<Siparis> siparisler;
    private ArrayList<Siparis> tamamlanmisSiparisler = new ArrayList<>();
    
    // GUI VARIABLES
    private Box box;
    
    /**
     * Creates new form SiparisEkranı
     */
    
    // CONSTRUCTOR
    public SiparisEkranı() {
        initComponents();
        UpdateTable();
    }
    
    
    // TABLE UPDATE
    private void UpdateTable(){
        JavaDBtoObj dbTOobj = new JavaDBtoObj();
        siparisler = dbTOobj.fetchDB();
        
        for( int i = 0; i < siparisler.size(); i++) {
            if( siparisler.get(i).getDurum().equals("Hazırlanıyor")){     //Tamamlandı
                tamamlanmisSiparisler.add( siparisler.get(i));
                siparisler.remove(i);
            }
        }
        
        System.out.println("Creating table object");
        
        String[] colum_namesAktif = {"Sipariş ID", "Firma", "Sipariş Tarihi", "Toplam Fiyat" };
        Object[][] Aktif = new Object[siparisler.size()][4];
        for ( int i = 0; i < siparisler.size(); i++) {
            Aktif[i][0] = siparisler.get(i).getSiparis_id();
            Aktif[i][1] = siparisler.get(i).getFirma().getFirma_adi();
            Aktif[i][2] = siparisler.get(i).getSiparis_tarih();
            Aktif[i][3] = siparisler.get(i).getToplam();
        }
        System.out.println("Setting new table model");
        DefaultTableModel tableModelAktif = new DefaultTableModel(Aktif, colum_namesAktif) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        
        aktif_siparis_table.setModel( tableModelAktif);
        aktif_siparis_table.setAutoCreateRowSorter( true);
        aktif_siparis_table.setRowSelectionAllowed( true);
        
        
        String[] colum_namesBitmis = {"Sipariş ID", "Firma", "Sipariş Tarihi", "Toplam Fiyat" };
        Object[][] Bitmis = new Object[tamamlanmisSiparisler.size()][4];
        for ( int i = 0; i < tamamlanmisSiparisler.size(); i++) {
            Bitmis[i][0] = tamamlanmisSiparisler.get(i).getSiparis_id();
            Bitmis[i][1] = tamamlanmisSiparisler.get(i).getFirma().getFirma_adi();
            Bitmis[i][2] = tamamlanmisSiparisler.get(i).getSiparis_tarih();
            Bitmis[i][3] = tamamlanmisSiparisler.get(i).getToplam();
        }
        System.out.println("Setting new table model");
        DefaultTableModel tableModelPasif = new DefaultTableModel(Bitmis, colum_namesBitmis) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        
        bitmis_siparis_table.setModel( tableModelPasif);
        bitmis_siparis_table.setAutoCreateRowSorter( true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siparisSekmeleri = new javax.swing.JTabbedPane();
        yeniSiparisGirisPaneli = new javax.swing.JPanel();
        yeniSiparis_FirmaPaneli = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        sg_aciklamaField2 = new javax.swing.JTextArea();
        sg_telField2 = new javax.swing.JTextField();
        sg_faxField2 = new javax.swing.JTextField();
        sg_ilgiliField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        sg_aciklama2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sg_mailField2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sg_gsmField2 = new javax.swing.JTextField();
        sg_firmaField2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        dateChooserCombo5 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo6 = new datechooser.beans.DateChooserCombo();
        yeniSiparis_urunlerPaneli = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        yeniSiparis_butons = new javax.swing.JPanel();
        sg_duzenle4 = new javax.swing.JButton();
        sg_sil4 = new javax.swing.JButton();
        sg_Kaydet4 = new javax.swing.JButton();
        aktifSiparislerPaneli = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aktif_siparis_table = new javax.swing.JTable();
        tamamlanmısSiparisPaneli = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bitmis_siparis_table = new javax.swing.JTable();
        siparisGoruntulemePaneli = new javax.swing.JPanel();
        siparisGoruntule_FirmaPaneli = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        sg_aciklamaField = new javax.swing.JTextArea();
        sg_telField = new javax.swing.JTextField();
        sg_faxField = new javax.swing.JTextField();
        sg_ilgiliField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sg_aciklama = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sg_mailField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sg_gsmField = new javax.swing.JTextField();
        sg_firmaField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        siparisGoruntule_urunlerPaneli = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        siparisGoruntule_butons = new javax.swing.JPanel();
        sg_duzenle = new javax.swing.JButton();
        sg_sil = new javax.swing.JButton();
        sg_Kaydet = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Akarsu Sipariş Takip Sistemi");

        yeniSiparis_FirmaPaneli.setBorder(javax.swing.BorderFactory.createTitledBorder("Sipariş Bilgileri"));

        sg_aciklamaField2.setColumns(20);
        sg_aciklamaField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sg_aciklamaField2.setRows(5);
        sg_aciklamaField2.setText("Bu bir açıklama örneğidir.");
        sg_aciklamaField2.setMinimumSize(new java.awt.Dimension(200, 19));
        jScrollPane8.setViewportView(sg_aciklamaField2);

        sg_telField2.setText("03122270408");

        sg_faxField2.setText("03122270409");

        sg_ilgiliField2.setText("Tansel Altınel");
        sg_ilgiliField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sg_ilgiliField2ActionPerformed(evt);
            }
        });

        jLabel19.setText("<html><b>Firma:</b></html>");

        sg_aciklama2.setText("<html><b>Açıklama</b><html>");

        jLabel20.setText("<html><b>Tel:</b></html>");

        sg_mailField2.setText("altinel@fumera.com.tr");

        jLabel21.setText("<html><b>E-Posta:</b></html>");

        jLabel22.setText("<html><b>Fax:</b></html>");

        jLabel23.setText("<html><b>İlgili:</b></html>");

        jLabel24.setText("<html><b>GSM:</b></html>");

        sg_gsmField2.setText("05312831924");

        sg_firmaField2.setText("Fumera Ar-Ge Yazılım Ltd. Şti.");
        sg_firmaField2.setMinimumSize(new java.awt.Dimension(200, 20));
        sg_firmaField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sg_firmaField2ActionPerformed(evt);
            }
        });

        jLabel27.setText("<html><b>Siparişi İsteyen:</b></html>");

        jLabel28.setText("<html><b>Siparişi Alan:</b></html>");

        jLabel29.setText("<html><b>Sipariş Tarihi:</b></html>");

        jLabel30.setText("<html><b>İstenilen Teslim Tarihi:</b></html>");

        jTextField8.setText("Tansel Altınel");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setText("Mustafa Akarsu");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        dateChooserCombo5.setLocale(new java.util.Locale("tr", "TR", ""));

        dateChooserCombo6.setLocale(new java.util.Locale("tr", "TR", ""));

        javax.swing.GroupLayout yeniSiparis_FirmaPaneliLayout = new javax.swing.GroupLayout(yeniSiparis_FirmaPaneli);
        yeniSiparis_FirmaPaneli.setLayout(yeniSiparis_FirmaPaneliLayout);
        yeniSiparis_FirmaPaneliLayout.setHorizontalGroup(
            yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniSiparis_FirmaPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_aciklama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(jTextField9)
                    .addComponent(jTextField8)
                    .addComponent(sg_faxField2)
                    .addComponent(sg_gsmField2)
                    .addComponent(sg_telField2)
                    .addComponent(sg_mailField2)
                    .addComponent(sg_ilgiliField2)
                    .addComponent(sg_firmaField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        yeniSiparis_FirmaPaneliLayout.setVerticalGroup(
            yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniSiparis_FirmaPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_firmaField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_ilgiliField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_mailField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_telField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_gsmField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_faxField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yeniSiparis_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sg_aciklama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        yeniSiparis_urunlerPaneli.setBorder(javax.swing.BorderFactory.createTitledBorder("Ürünler"));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable3);

        javax.swing.GroupLayout yeniSiparis_urunlerPaneliLayout = new javax.swing.GroupLayout(yeniSiparis_urunlerPaneli);
        yeniSiparis_urunlerPaneli.setLayout(yeniSiparis_urunlerPaneliLayout);
        yeniSiparis_urunlerPaneliLayout.setHorizontalGroup(
            yeniSiparis_urunlerPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
        );
        yeniSiparis_urunlerPaneliLayout.setVerticalGroup(
            yeniSiparis_urunlerPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        sg_duzenle4.setText("Temizle");
        sg_duzenle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sg_duzenle4ActionPerformed(evt);
            }
        });

        sg_sil4.setText("İptal");

        sg_Kaydet4.setText("Kaydet");
        sg_Kaydet4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sg_Kaydet4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout yeniSiparis_butonsLayout = new javax.swing.GroupLayout(yeniSiparis_butons);
        yeniSiparis_butons.setLayout(yeniSiparis_butonsLayout);
        yeniSiparis_butonsLayout.setHorizontalGroup(
            yeniSiparis_butonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniSiparis_butonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sg_duzenle4)
                .addGap(18, 18, 18)
                .addComponent(sg_sil4)
                .addGap(18, 18, 18)
                .addComponent(sg_Kaydet4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        yeniSiparis_butonsLayout.setVerticalGroup(
            yeniSiparis_butonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniSiparis_butonsLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(yeniSiparis_butonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sg_duzenle4)
                    .addComponent(sg_sil4)
                    .addComponent(sg_Kaydet4))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout yeniSiparisGirisPaneliLayout = new javax.swing.GroupLayout(yeniSiparisGirisPaneli);
        yeniSiparisGirisPaneli.setLayout(yeniSiparisGirisPaneliLayout);
        yeniSiparisGirisPaneliLayout.setHorizontalGroup(
            yeniSiparisGirisPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniSiparisGirisPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yeniSiparisGirisPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yeniSiparis_FirmaPaneli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yeniSiparis_urunlerPaneli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yeniSiparis_butons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        yeniSiparisGirisPaneliLayout.setVerticalGroup(
            yeniSiparisGirisPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniSiparisGirisPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yeniSiparis_FirmaPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yeniSiparis_urunlerPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(yeniSiparis_butons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        siparisSekmeleri.addTab("Yeni Sipariş Girişi", yeniSiparisGirisPaneli);

        aktif_siparis_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aktif_siparis_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(aktif_siparis_table);
        aktif_siparis_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout aktifSiparislerPaneliLayout = new javax.swing.GroupLayout(aktifSiparislerPaneli);
        aktifSiparislerPaneli.setLayout(aktifSiparislerPaneliLayout);
        aktifSiparislerPaneliLayout.setHorizontalGroup(
            aktifSiparislerPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        aktifSiparislerPaneliLayout.setVerticalGroup(
            aktifSiparislerPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );

        siparisSekmeleri.addTab("Aktif Siparişler", aktifSiparislerPaneli);

        bitmis_siparis_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bitmis_siparis_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bitmis_siparis_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(bitmis_siparis_table);

        javax.swing.GroupLayout tamamlanmısSiparisPaneliLayout = new javax.swing.GroupLayout(tamamlanmısSiparisPaneli);
        tamamlanmısSiparisPaneli.setLayout(tamamlanmısSiparisPaneliLayout);
        tamamlanmısSiparisPaneliLayout.setHorizontalGroup(
            tamamlanmısSiparisPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        tamamlanmısSiparisPaneliLayout.setVerticalGroup(
            tamamlanmısSiparisPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );

        siparisSekmeleri.addTab("Tamamlanmış Siparişler", tamamlanmısSiparisPaneli);

        siparisGoruntule_FirmaPaneli.setBorder(javax.swing.BorderFactory.createTitledBorder("Sipariş Bilgileri"));

        sg_aciklamaField.setEditable(false);
        sg_aciklamaField.setColumns(20);
        sg_aciklamaField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sg_aciklamaField.setRows(5);
        sg_aciklamaField.setText("Bu bir açıklama örneğidir.");
        sg_aciklamaField.setMinimumSize(new java.awt.Dimension(200, 19));
        jScrollPane4.setViewportView(sg_aciklamaField);

        sg_telField.setEditable(false);
        sg_telField.setText("03122270408");

        sg_faxField.setEditable(false);
        sg_faxField.setText("03122270409");

        sg_ilgiliField.setEditable(false);
        sg_ilgiliField.setText("Tansel Altınel");
        sg_ilgiliField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sg_ilgiliFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("<html><b>Firma:</b></html>");

        sg_aciklama.setText("<html><b>Açıklama</b><html>");

        jLabel4.setText("<html><b>Tel:</b></html>");

        sg_mailField.setEditable(false);
        sg_mailField.setText("altinel@fumera.com.tr");

        jLabel3.setText("<html><b>E-Posta:</b></html>");

        jLabel6.setText("<html><b>Fax:</b></html>");

        jLabel2.setText("<html><b>İlgili:</b></html>");

        jLabel5.setText("<html><b>GSM:</b></html>");

        sg_gsmField.setEditable(false);
        sg_gsmField.setText("05312831924");

        sg_firmaField.setEditable(false);
        sg_firmaField.setText("Fumera Ar-Ge Yazılım Ltd. Şti.");
        sg_firmaField.setMinimumSize(new java.awt.Dimension(200, 20));
        sg_firmaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sg_firmaFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("<html><b>Siparişi İsteyen:</b></html>");

        jLabel9.setText("<html><b>Siparişi Alan:</b></html>");

        jLabel10.setText("<html><b>Sipariş Tarihi:</b></html>");

        jLabel11.setText("<html><b>İstenilen Teslim Tarihi:</b></html>");

        jTextField4.setEditable(false);
        jTextField4.setText("Tansel Altınel");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField6.setEditable(false);
        jTextField6.setText("Mustafa Akarsu");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        dateChooserCombo1.setLocale(new java.util.Locale("tr", "TR", ""));

        dateChooserCombo2.setLocale(new java.util.Locale("tr", "TR", ""));

        javax.swing.GroupLayout siparisGoruntule_FirmaPaneliLayout = new javax.swing.GroupLayout(siparisGoruntule_FirmaPaneli);
        siparisGoruntule_FirmaPaneli.setLayout(siparisGoruntule_FirmaPaneliLayout);
        siparisGoruntule_FirmaPaneliLayout.setHorizontalGroup(
            siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siparisGoruntule_FirmaPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_aciklama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jTextField4)
                    .addComponent(sg_faxField)
                    .addComponent(sg_gsmField)
                    .addComponent(sg_telField)
                    .addComponent(sg_mailField)
                    .addComponent(sg_ilgiliField)
                    .addComponent(sg_firmaField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        siparisGoruntule_FirmaPaneliLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel8, jLabel9, sg_aciklama});

        siparisGoruntule_FirmaPaneliLayout.setVerticalGroup(
            siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siparisGoruntule_FirmaPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_firmaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_ilgiliField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_telField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_gsmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_faxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siparisGoruntule_FirmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sg_aciklama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        siparisGoruntule_FirmaPaneliLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel8, jLabel9, sg_aciklama});

        siparisGoruntule_urunlerPaneli.setBorder(javax.swing.BorderFactory.createTitledBorder("Ürünler"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        javax.swing.GroupLayout siparisGoruntule_urunlerPaneliLayout = new javax.swing.GroupLayout(siparisGoruntule_urunlerPaneli);
        siparisGoruntule_urunlerPaneli.setLayout(siparisGoruntule_urunlerPaneliLayout);
        siparisGoruntule_urunlerPaneliLayout.setHorizontalGroup(
            siparisGoruntule_urunlerPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
        );
        siparisGoruntule_urunlerPaneliLayout.setVerticalGroup(
            siparisGoruntule_urunlerPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        sg_duzenle.setText("Düzenle");
        sg_duzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sg_duzenleActionPerformed(evt);
            }
        });

        sg_sil.setText("Sil");

        sg_Kaydet.setText("Kaydet");
        sg_Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sg_KaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siparisGoruntule_butonsLayout = new javax.swing.GroupLayout(siparisGoruntule_butons);
        siparisGoruntule_butons.setLayout(siparisGoruntule_butonsLayout);
        siparisGoruntule_butonsLayout.setHorizontalGroup(
            siparisGoruntule_butonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siparisGoruntule_butonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sg_duzenle)
                .addGap(18, 18, 18)
                .addComponent(sg_sil)
                .addGap(18, 18, 18)
                .addComponent(sg_Kaydet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        siparisGoruntule_butonsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {sg_Kaydet, sg_duzenle, sg_sil});

        siparisGoruntule_butonsLayout.setVerticalGroup(
            siparisGoruntule_butonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siparisGoruntule_butonsLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(siparisGoruntule_butonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sg_duzenle)
                    .addComponent(sg_sil)
                    .addComponent(sg_Kaydet))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout siparisGoruntulemePaneliLayout = new javax.swing.GroupLayout(siparisGoruntulemePaneli);
        siparisGoruntulemePaneli.setLayout(siparisGoruntulemePaneliLayout);
        siparisGoruntulemePaneliLayout.setHorizontalGroup(
            siparisGoruntulemePaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siparisGoruntulemePaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(siparisGoruntulemePaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(siparisGoruntule_FirmaPaneli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siparisGoruntule_urunlerPaneli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siparisGoruntule_butons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        siparisGoruntulemePaneliLayout.setVerticalGroup(
            siparisGoruntulemePaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siparisGoruntulemePaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(siparisGoruntule_FirmaPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(siparisGoruntule_urunlerPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(siparisGoruntule_butons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        siparisSekmeleri.addTab("Sipariş Görüntüle", siparisGoruntulemePaneli);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );

        siparisSekmeleri.addTab("Silinmiş Siparişler", jPanel2);

        jMenu1.setText("Dosya");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setLabel("Çıkış");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kullanıcılar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayarlar");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Yardım");

        jMenuItem2.setText("Yardım");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Hakkında");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(siparisSekmeleri)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(siparisSekmeleri)
        );

        siparisSekmeleri.getAccessibleContext().setAccessibleName("Aktif Siparişler");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Fumera Ar-Ge Yazılım Ltd. Şti. \n Yazılım Departmanı\nTansel Altınel\naltinel@fumera.com.tr", "Hakkında", JOptionPane.INFORMATION_MESSAGE, null);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void aktif_siparis_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aktif_siparis_tableMouseClicked
        // TODO add your handling code here:
        if( evt.getClickCount() >= 2) {
            String siparis_id_temp = "0";
            try {
                int row = aktif_siparis_table.getSelectedRow();
                siparis_id_temp = aktif_siparis_table.getModel().getValueAt( row, 0).toString();
                System.out.println( siparis_id_temp);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            siparisGoruntule( siparis_id_temp, true);
        }
    }//GEN-LAST:event_aktif_siparis_tableMouseClicked

    private void sg_duzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sg_duzenleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sg_duzenleActionPerformed

    private void sg_KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sg_KaydetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sg_KaydetActionPerformed

    private void bitmis_siparis_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bitmis_siparis_tableMouseClicked
        if( evt.getClickCount() >= 2) {
            String siparis_id_temp = "0";
            try {
                int row = bitmis_siparis_table.getSelectedRow();
                siparis_id_temp = bitmis_siparis_table.getModel().getValueAt( row, 0).toString();
                System.out.println( siparis_id_temp);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            siparisGoruntule( siparis_id_temp, false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bitmis_siparis_tableMouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void sg_firmaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sg_firmaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sg_firmaFieldActionPerformed

    private void sg_ilgiliFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sg_ilgiliFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sg_ilgiliFieldActionPerformed

    private void sg_ilgiliField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sg_ilgiliField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sg_ilgiliField2ActionPerformed

    private void sg_firmaField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sg_firmaField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sg_firmaField2ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void sg_duzenle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sg_duzenle4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sg_duzenle4ActionPerformed

    private void sg_Kaydet4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sg_Kaydet4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sg_Kaydet4ActionPerformed

    private void siparisGoruntule( String id, boolean aktif){
        int i = Integer.parseInt(id);
        Siparis siparis = null;

        if( aktif) {
            for( int k = 0; k < siparisler.size(); k++){
                if( siparisler.get(k).getSiparis_id() == i) {
                    //siparis = siparisler.get(k);
                    //System.out.println(k);
                    sg_firmaField.setText( siparisler.get(k).getFirma().getFirma_adi());
                    System.out.println(siparisler.get(k).getFirma().getFirma_adi());
                    sg_ilgiliField.setText( siparisler.get(k).getFirma().getIlgili_adi());
                    sg_mailField.setText( siparisler.get(k).getFirma().getMail());
                    sg_telField.setText( siparisler.get(k).getFirma().getTel());
                    sg_gsmField.setText( siparisler.get(k).getFirma().getGsm());
                    sg_faxField.setText( siparisler.get(k).getFirma().getFax());
                    sg_aciklamaField.setText( siparisler.get(k).getAciklama());
                }
            }
        } else {
            for( int k = 0; k < tamamlanmisSiparisler.size(); k++){
                if( tamamlanmisSiparisler.get(k).getSiparis_id() == i) {
                    //siparis = tamamlanmisSiparisler.get(k);
                    //System.out.println(k);
                    sg_firmaField.setText( tamamlanmisSiparisler.get(k).getFirma().getFirma_adi());
                    sg_ilgiliField.setText( tamamlanmisSiparisler.get(k).getFirma().getIlgili_adi());
                    sg_mailField.setText( tamamlanmisSiparisler.get(k).getFirma().getMail());
                    sg_telField.setText( tamamlanmisSiparisler.get(k).getFirma().getTel());
                    sg_gsmField.setText( tamamlanmisSiparisler.get(k).getFirma().getGsm());
                    sg_faxField.setText( tamamlanmisSiparisler.get(k).getFirma().getFax());
                    sg_aciklamaField.setText( tamamlanmisSiparisler.get(k).getAciklama());
                }
            }

        }
        siparisSekmeleri.setSelectedIndex(3);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SiparisEkranı().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aktifSiparislerPaneli;
    private javax.swing.JTable aktif_siparis_table;
    private javax.swing.JTable bitmis_siparis_table;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private datechooser.beans.DateChooserCombo dateChooserCombo5;
    private datechooser.beans.DateChooserCombo dateChooserCombo6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton sg_Kaydet;
    private javax.swing.JButton sg_Kaydet1;
    private javax.swing.JButton sg_Kaydet2;
    private javax.swing.JButton sg_Kaydet3;
    private javax.swing.JButton sg_Kaydet4;
    private javax.swing.JLabel sg_aciklama;
    private javax.swing.JLabel sg_aciklama2;
    private javax.swing.JTextArea sg_aciklamaField;
    private javax.swing.JTextArea sg_aciklamaField2;
    private javax.swing.JButton sg_duzenle;
    private javax.swing.JButton sg_duzenle1;
    private javax.swing.JButton sg_duzenle2;
    private javax.swing.JButton sg_duzenle3;
    private javax.swing.JButton sg_duzenle4;
    private javax.swing.JTextField sg_faxField;
    private javax.swing.JTextField sg_faxField2;
    private javax.swing.JTextField sg_firmaField;
    private javax.swing.JTextField sg_firmaField2;
    private javax.swing.JTextField sg_gsmField;
    private javax.swing.JTextField sg_gsmField2;
    private javax.swing.JTextField sg_ilgiliField;
    private javax.swing.JTextField sg_ilgiliField2;
    private javax.swing.JTextField sg_mailField;
    private javax.swing.JTextField sg_mailField2;
    private javax.swing.JButton sg_sil;
    private javax.swing.JButton sg_sil1;
    private javax.swing.JButton sg_sil2;
    private javax.swing.JButton sg_sil3;
    private javax.swing.JButton sg_sil4;
    private javax.swing.JTextField sg_telField;
    private javax.swing.JTextField sg_telField2;
    private javax.swing.JPanel siparisGoruntule_FirmaPaneli;
    private javax.swing.JPanel siparisGoruntule_butons;
    private javax.swing.JPanel siparisGoruntule_butons1;
    private javax.swing.JPanel siparisGoruntule_butons2;
    private javax.swing.JPanel siparisGoruntule_butons3;
    private javax.swing.JPanel siparisGoruntule_urunlerPaneli;
    private javax.swing.JPanel siparisGoruntulemePaneli;
    private javax.swing.JTabbedPane siparisSekmeleri;
    private javax.swing.JPanel tamamlanmısSiparisPaneli;
    private javax.swing.JPanel yeniSiparisGirisPaneli;
    private javax.swing.JPanel yeniSiparis_FirmaPaneli;
    private javax.swing.JPanel yeniSiparis_butons;
    private javax.swing.JPanel yeniSiparis_urunlerPaneli;
    // End of variables declaration//GEN-END:variables
}